kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-data
  labels:
    name: gitlab-data
spec:
  capacity:
    storage: "8Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/gitlab-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "gitlab-data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data
  labels:
    name: postgresql-data
spec:
  capacity:
    storage: "8Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/postgresql-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: "postgresql-data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data
  labels:
    name: redis-data
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/redis-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: "redis-data"
